#!/usr/bin/env python3
"""Build the Box API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'File Requests': 'File Reqs',
    'Folder Locks': 'Folder Locks',
    'Metadata Templates': 'MD Templates',
    'Metadata Cascade': 'MD Cascade',
    'Metadata Queries': 'MD Queries',
    'Task Assignments': 'Task Assigns',
    'Shared Items': 'Shared Items',
    'Skill Invocations': 'Skill Inv.',
    'Retention Policies': 'Retention',
    'Legal Holds': 'Legal Holds',
    'Storage Policies': 'Storage Pol',
    'Device Pinners': 'Device Pinners',
    'Sign Requests': 'Sign Reqs',
    'Sign Templates': 'Sign Tmpls',
    'Zip Downloads': 'Zip DL',
}

LINES = [
    {
        "name": 'Files & Folders',
        "color": '#0061D5',
        "stations": [
        ('Files', (270, 195)),
        ('File Requests', (430, 175)),
        ('Folders', (590, 165)),
        ('Folder Locks', (760, 175)),
        ('Web Links', (940, 200)),
        ],
    },
    {
        "name": 'Metadata & Search',
        "color": '#0E9D6E',
        "stations": [
        ('Metadata Templates', (270, 310)),
        ('Metadata Cascade', (450, 285)),
        ('Metadata Queries', (640, 285)),
        ('Search', (820, 285)),
        ],
    },
    {
        "name": 'Collaboration & Tasks',
        "color": '#E68B1F',
        "stations": [
        ('Comments', (270, 425)),
        ('Collaborations', (430, 405)),
        ('Tasks', (610, 405)),
        ('Task Assignments', (790, 405)),
        ('Shared Items', (970, 425)),
        ],
    },
    {
        "name": 'Identity & Auth',
        "color": '#7B3FE4',
        "stations": [
        ('Authorize', (270, 540)),
        ('OAuth2', (430, 515)),
        ('Users', (610, 515)),
        ('Groups', (790, 540)),
        ('Enterprises', (960, 565)),
        ],
    },
    {
        "name": 'Events & Webhooks',
        "color": '#C5318B',
        "stations": [
        ('Webhooks', (270, 660)),
        ('Skill Invocations', (450, 635)),
        ('Events', (640, 635)),
        ('Collections', (820, 660)),
        ],
    },
    {
        "name": 'Compliance & Retention',
        "color": '#1E5BD0',
        "stations": [
        ('Retention Policies', (270, 770)),
        ('Legal Holds', (470, 745)),
        ('Storage Policies', (660, 745)),
        ('Device Pinners', (840, 770)),
        ],
    },
    {
        "name": 'Sign & Workflows',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Sign Requests', (790, 815)),
        ('Sign Templates', (905, 815)),
        ('Workflows', (790, 815)),
        ('Zip Downloads', (675, 815)),
        ],
    },
]

URL_OVERRIDES = {
    'Authorize': 'https://apis.apis.io/apis/box/box-authorize-api/',
    'OAuth2': 'https://apis.apis.io/apis/box/box-oauth2-api/',
    'Files': 'https://apis.apis.io/apis/box/box-files-api/',
    'File Requests': 'https://apis.apis.io/apis/box/box-file-requests-api/',
    'Folders': 'https://apis.apis.io/apis/box/box-folders-api/',
    'Folder Locks': 'https://apis.apis.io/apis/box/box-folder-locks-api/',
    'Web Links': 'https://apis.apis.io/apis/box/box-web-links-api/',
    'Metadata Templates': 'https://apis.apis.io/apis/box/box-metadata-templates-api/',
    'Metadata Cascade': 'https://apis.apis.io/apis/box/box-metadata-cascade-policies-api/',
    'Metadata Queries': 'https://apis.apis.io/apis/box/box-metadata-queries-api/',
    'Search': 'https://apis.apis.io/apis/box/box-search-api/',
    'Comments': 'https://apis.apis.io/apis/box/box-comments-api/',
    'Collaborations': 'https://apis.apis.io/apis/box/box-collaborations-api/',
    'Tasks': 'https://apis.apis.io/apis/box/box-tasks-api/',
    'Task Assignments': 'https://apis.apis.io/apis/box/box-task-assignments-api/',
    'Shared Items': 'https://apis.apis.io/apis/box/box-shared-items-api/',
    'Users': 'https://apis.apis.io/apis/box/box-users-api/',
    'Groups': 'https://apis.apis.io/apis/box/box-groups-api/',
    'Enterprises': 'https://apis.apis.io/apis/box/box-enterprises-api/',
    'Webhooks': 'https://apis.apis.io/apis/box/box-webhooks-api/',
    'Skill Invocations': 'https://apis.apis.io/apis/box/box-skill-invocations-api/',
    'Events': 'https://apis.apis.io/apis/box/box-events-api/',
    'Collections': 'https://apis.apis.io/apis/box/box-collections-api/',
    'Retention Policies': 'https://apis.apis.io/apis/box/box-retention-policies-api/',
    'Legal Holds': 'https://apis.apis.io/apis/box/box-legal-hold-policies-api/',
    'Storage Policies': 'https://apis.apis.io/apis/box/box-storage-policies-api/',
    'Device Pinners': 'https://apis.apis.io/apis/box/box-device-pinners-api/',
    'Sign Requests': 'https://apis.apis.io/apis/box/box-sign-requests-api/',
    'Sign Templates': 'https://apis.apis.io/apis/box/box-sign-templates-api/',
    'Workflows': 'https://apis.apis.io/apis/box/box-workflows-api/',
    'Zip Downloads': 'https://apis.apis.io/apis/box/box-zip-downloads-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Box API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: box/openapi · github.com/api-evangelist/box',
        out_dir=Path(__file__).resolve().parent,
        out_basename='box-subway-map',
        provider_id='box',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
